export const SERVICE_ROLES = [
    'LEAD PHOTOGRAPHER',
    'LEAD CANDID PHOTOGRAPHER',
    'LEAD CINEMATOGRAPHER',
    'CONVENTIONAL PHOTOGRAPHER',
    'CONVENTIONAL VIDEOGRAPHER',
    'SPOT EDITOR',
    'EDITOR',
    'DRONE OPERATOR',
    'ASSISTANT',
    'LIVE STREAMER',
    'LED WALL OPERATOR'
];
